name: build-test
on:
  # schedule: [{cron: '0 0 * * *'}]
  push: {branches: main}
  pull_request:
jobs:
  install-agda:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Setup Agda
        uses: omelkonian/setup-agda@main
        with:
          agda-version: 2.8.0
          stdlib-version: 2.3
          libraries: |
            agda/agda-stdlib-classes#v2.3
            agda/agda-stdlib-meta#v2.3
          cache: false
          dir: Example
          main: Test
          deploy: ${{ github.ref == 'refs/heads/main' }}
          token: ${{ secrets.GITHUB_TOKEN }}
          ribbon: true
          rts: -K256M -H1G -M8G -A128M
          measure-typechecking: true
