name: build-test
on:
  # schedule: [{cron: '0 0 * * *'}]
  push: {branches: master}
jobs:
  install-agda:
    name: Agda-2.6.1, sdtlib-1.3
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.1
      - uses: omelkonian/setup-agda@master
        with:
          agda-version: 2.6.1
          stdlib-version: 1.3
          libraries: |
            omelkonian/formal-prelude#1849
            omelkonian/formal-bitcoin#54c4
            omelkonian/formal-bitml#SRC-paper
          main: Example/Test
          token: ${{ secrets.GITHUB_TOKEN }}
          ribbon: true
          rts: -K256M -H1G -M8G -A128M

