name: build-test
on:
  push:
    branches:
      - master
jobs:
  install-agda:
    name: Agda ${{ matrix.agda }}, stdlib ${{ matrix.stdlib }} - ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest] #, macOS-latest]
        agda: ['latest'] #, '2.6.0']
        stdlib: ['latest'] #, '1.2']

    steps:
      - uses: actions/checkout@v2
      - uses: omelkonian/setup-agda@test
        with:
          agda-version: ${{ matrix.agda }}
          stdlib-version: ${{ matrix.stdlib }}
          libraries: 'omelkonian:formal-prelude,omelkonian:formal-bitcoin'
      - shell: bash
        run: agda Test.agda
