name: build-test
on:
  # schedule: [{cron: '0 0 * * *'}]
  push: {branches: master}
  pull_request:
jobs:
  install-agda:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: omelkonian/setup-agda@master
        with:
          agda-version: 2.6.3
          stdlib-version: 1.7.2
          libraries: |
            omelkonian/formal-prelude#c10fe94
            omelkonian/formal-bitcoin#54c4
            omelkonian/formal-bitml#SRC-paper
          main: Example/Test
          deploy: ${{ github.ref == 'refs/heads/master' }}
          token: ${{ secrets.GITHUB_TOKEN }}
          ribbon: true
          rts: -K256M -H1G -M8G -A128M
          measure-typechecking: true
